### ISSUE TITLE
Zombie Nation support

### ISSUE THREAD

**Issue by DrAzathoth** [Infinest/Gimmick-ROM-extractor#1]
Could you add support for Zombie Nation? It appears to use the same emulation setup with an "AR_win32.mdf" file.

https://store.steampowered.com/app/1603920/__ZOMBIE_NATION/

**Comment by Infinest** [comment]
Please give this a try and see if it works for you:
https://github.com/Infinest/Gimmick-ROM-extractor/releases/tag/1.1

### Instructions:

- Extract "Gimmick_ROM_extractor.exe" and "alternate_configs/Abarenbo Tengu & Zombie Nation/config.json" to the directory where your "AR_win32.mdf" file is located.
Do not use the "config.json" located in the root of the zip. That one is meant for Gimmick! and will not work with Zombie Nation.
- Then just run "Gimmick_ROM_extractor.exe" and confirm the extraction. It should give you both "Abarenbou Tengu (Japan).nes" and "Zombie Nation (USA).nes".

Please give me some feedback once you're done testing.

**Comment by kjetil-f** [comment]
Can confirm it works. Thanks!
