### ISSUE TITLE
F-117A Stealth Fighter support

### ISSUE THREAD

**Issue by DrAzathoth** [Infinest/Gimmick-ROM-extractor#2]
F-117A seems to have the same setup. Could support for this game be added as well?

https://store.steampowered.com/app/1245170/F117A_Stealth_Fighter_NES_edition/

**Comment by Infinest** [comment]
I've added compatibility with the linked Steam release.
The INES header is slightly different from the ROM i have on hand however:
![image](https://github.com/Infinest/Gimmick-ROM-extractor/assets/7109154/1bc235e0-5b9f-4bf5-8727-aff20cbaaff5)

The ROM seems to boot in an emulator but it would be helpful if you could check to see if any additional modifications to the INES header of the extracted ROM are necessary or not.

Here's the link to the pre-release:
https://github.com/Infinest/Gimmick-ROM-extractor/releases/tag/1.2

**Comment by DrAzathoth** [comment]
@Infinest, the new update works perfectly. The ROM extracted is absolutely identical to the original one aside from the header. As for the header discrepancy, the header of the extracted ROM is outdated and yours is a more recent one. The old one should work perfectly fine, but for the most accurate emulation, the newest one should be used instead.

For reference, here is the most up-to-date iNES header for the game that I know of:
`4E 45 53 1A 10 20 40 08 00 00 00 00 00 00 00 01`

**Comment by Infinest** [comment]
@DrAzathoth I've added another new key to the config.json files to allow specifying fixed iNES headers. If one is specified in the used config.json the application now asks if the fixed header should be applied or not. I've added the correct No-Intro headers to all config.json files (Gimmick, Abarenbo Tengu & Zombie Nation, F-117A Stealth Fighter). The linked pre-release has been updated.

I've noticed the new pre-release is currently being detected as a false-positive by Windows Defender for whatever reason and no matter what changes i make it keeps being detected. I will keep it as a pre-release for now and submit the new executable to Microsoft. https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Infinest** [comment]
![image](https://github.com/Infinest/Gimmick-ROM-extractor/assets/7109154/3cd718f3-536a-4b24-999b-4534a460136d)

They still have not responded to my file submission. They did however seemingly fix something about their cloud detection service incorrectly detecting the new release as a virus. I just retriggered the automatic scan and it's giving me all checkmarks.
Windows Defender also doesn't detect it anymore. I'll mark the pre-release as the new latest now as the issue seems to be resolved.
